let data = [
  {
      "type":"heading_open",
      "tag":"h1",
      "attrs":null,
      "map":[
          0,
          2
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"=",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
     
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"一级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"一级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h1",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"=",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          3,
          4
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          3,
          4
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"一",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"strong_open",
              "tag":"strong",
              "attrs":null,
              "map":null,
              "nesting":1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"**",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":1,
              "children":null,
              "content":"级标题内容",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"strong_close",
              "tag":"strong",
              "attrs":null,
              "map":null,
              "nesting":-1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"**",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"......对对对",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"一**级标题内容**......对对对",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_open",
      "tag":"h2",
      "attrs":null,
      "map":[
          5,
          7
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"-",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          5,
          6
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"二级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"二级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h2",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"-",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          8,
          9
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          8,
          9
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"二级标",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"strong_open",
              "tag":"strong",
              "attrs":null,
              "map":null,
              "nesting":1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"**",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":1,
              "children":null,
              "content":"题正",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"strong_close",
              "tag":"strong",
              "attrs":null,
              "map":null,
              "nesting":-1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"**",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"文内容...对对对...",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"二级标**题正**文内容...对对对...",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          10,
          11
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          10,
          11
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"[二级标题]{.underline}又一段对的",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"[二级标题]{.underline}又一段对的",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_open",
      "tag":"h3",
      "attrs":null,
      "map":[
          12,
          13
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"###",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          12,
          13
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"三级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"三级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h3",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"###",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          14,
          15
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          14,
          15
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"em_open",
              "tag":"em",
              "attrs":null,
              "map":null,
              "nesting":1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"*",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":1,
              "children":null,
              "content":"三级",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"em_close",
              "tag":"em",
              "attrs":null,
              "map":null,
              "nesting":-1,
              "level":0,
              "children":null,
              "content":"",
              "markup":"*",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          },
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"标题正文内容......",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"*三级*标题正文内容......",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          16,
          17
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          16,
          17
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"三级标题有一单",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"三级标题有一单",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_open",
      "tag":"h2",
      "attrs":null,
      "map":[
          18,
          20
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"-",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          18,
          19
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"二级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"二级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h2",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"-",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          21,
          22
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          21,
          22
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"二级标题内容",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"二级标题内容",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_open",
      "tag":"h3",
      "attrs":null,
      "map":[
          23,
          24
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"###",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          23,
          24
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"又一个三级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"又一个三级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h3",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"###",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          25,
          26
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          25,
          26
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"三级笔筒",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"三级笔筒",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          27,
          28
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          27,
          28
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"股互惠",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"股互惠",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_open",
      "tag":"h4",
      "attrs":null,
      "map":[
          29,
          30
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"####",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          29,
          30
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"四级标题",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"四级标题",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"heading_close",
      "tag":"h4",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"####",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          31,
          32
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          31,
          32
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"四级标题正文内容......",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"四级标题正文内容......",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_open",
      "tag":"p",
      "attrs":null,
      "map":[
          33,
          34
      ],
      "nesting":1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"inline",
      "tag":"",
      "attrs":null,
      "map":[
          33,
          34
      ],
      "nesting":0,
      "level":1,
      "children":[
          {
              "type":"text",
              "tag":"",
              "attrs":null,
              "map":null,
              "nesting":0,
              "level":0,
              "children":null,
              "content":"致谢:",
              "markup":"",
              "info":"",
              "meta":null,
              "block":false,
              "hidden":false
          }
      ],
      "content":"致谢:",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  },
  {
      "type":"paragraph_close",
      "tag":"p",
      "attrs":null,
      "map":null,
      "nesting":-1,
      "level":0,
      "children":null,
      "content":"",
      "markup":"",
      "info":"",
      "meta":null,
      "block":true,
      "hidden":false
  }
];

let content = {chapters: []};
let h1Flag = -1;
let h2Flag = -1;
let h3Flag = -1;
let h4Flag = -1;
let currentHeaderType = null;

function getTempObj(data, i) {
  return {
    name: data[i+1].content,
      preParagraphs: [],
      sections: []
  }
}

function getTempParagragh(data, i) {
  return {
    paragraph: data[i+1].content
  }
}

function setHeaderForContent(data, i) {
  if (data[i].tag === 'h1') {
    h1Flag += 1;
    h2Flag = -1;
    h3Flag = -1;
    h4Flag = -1;
    content.chapters.push(getTempObj(data, i));
  }
  if (data[i].tag === 'h2') {
    h2Flag += 1;
    h3Flag = -1;
    h4Flag = -1;
    content.chapters[h1Flag].sections.push(getTempObj(data, i));
  }
  if (data[i].tag === 'h3') {
    h3Flag +=1;
    h4Flag = -1;
    content.chapters[h1Flag].sections[h2Flag].sections.push(getTempObj(data, i));
  }
  if (data[i].tag === 'h4') {
    h4Flag +=1;
    content.chapters[h1Flag].sections[h2Flag].sections[h3Flag].sections.push(getTempObj(data, i));
  }
}

function setParagraphForHeader(data, i) {
  if (data[i-1].tag !== 'p') {
    currentHeaderType = data[i-1].tag;
  }
  if (currentHeaderType === 'h1') {
    content.chapters[h1Flag].preParagraphs.push(getTempParagragh(data, i));
  }
  if (currentHeaderType === 'h2') {
    content.chapters[h1Flag].sections[h2Flag].preParagraphs.push(getTempParagragh(data, i));
  }
  if (currentHeaderType === 'h3') {
    content.chapters[h1Flag].sections[h2Flag].sections[h3Flag].preParagraphs.push(getTempParagragh(data, i));
  }
  if (currentHeaderType === 'h4') {
    content.chapters[h1Flag].sections[h2Flag].sections[h3Flag].sections[h4Flag].preParagraphs.push(getTempParagragh(data, i));
  }
}

function arrayTranslateToTree(data) {
  for(let i = 0; i < data.length; i ++) {
    if (data[i].type === 'heading_open') {
      setHeaderForContent(data, i);
    }
    if (data[i].type === 'paragraph_open') {
      setParagraphForHeader(data, i);
    }
  }
  return content;
}

let newDate = arrayTranslateToTree(data);
console.log(newDate);
module.exports = {
  arrayTranslateToTree
};